version: '3'

services:
    app:
      build: 
        context: node
      container_name: app
      entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
      command: node_modules/.bin/nodemon --exec node index.js
      networks: 
        - node-network
      volumes: 
        - ./node:/usr/src/app
        - /usr/src/app/node_modules
      tty: true
      ports: 
        - "3000:3000"
      depends_on: 
        - db
    db:
      platform: linux/x86_64
      build: 
        context: mysql
      command: --innodb-use-native-aio=0
      container_name: db
      restart: always
      tty: true
      expose:
        - 3306
      volumes: 
        - ./mysql/volume:/var/lib/mysql
      networks: 
        - node-network
    nginx:
        build:
          context: nginx
        restart: always
        ports:
          - "8080:80"
        networks: 
          - node-network
        depends_on:
          - app
networks: 
  node-network:
    driver: bridge 